### ISSUE TITLE
最新镜像启动失败

### ISSUE THREAD

**Issue by LemonZuo** [Jonnyan404/cloud-clipboard-go#5]
> docker-compose.yml

```yaml
networks:
  compose_lan:
    external: true

services:
  cloud-clipboard-go:
    image: jonnyan404/cloud-clipboard-go:latest
    container_name: cloud-clipboard-go
    restart: unless-stopped
    environment:
      - LISTEN_IP= #默认为0.0.0.0,可设置为 127.0.0.1 不懂勿动
      - LISTEN_IP6= #默认为::1,ipv6地址,可设置为::,不懂勿动
      - LISTEN_PORT= #默认为9501,可设置为其他端口
      - PREFIX= #子路径,可配合nginx使用,格式: /cloud-clipboard
      - MESSAGE_NUM= #历史记录的数量,默认为10
      - AUTH_PASSWORD= #访问密码,默认为false,可自定义字符串密码
      - TEXT_LIMIT= #文本长度限制,默认为4096(2048个汉字),可设置为其他长度
      - FILE_EXPIRE= #文件过期时间,默认为3600(1小时),可设置为其他时间,单位为秒
      - FILE_LIMIT= #文件大小限制,默认为104857600(100MB),可设置为其他大小,单位为字节
      - MKCERT_DOMAIN_OR_IP= #mkcert域名或IP,默认为空,可设置为其他域名或IP,多个用空格分隔,仅域名支持通配符*
      - MANUAL_KEY_PATH= #手动设置证书路径,默认为空,该参数优先级高于MKCERT_DOMAIN_OR_IP
      - MANUAL_CERT_PATH= #手动设置证书路径,默认为空,该参数优先级高于MKCERT_DOMAIN_OR_IP
    networks:
      compose_lan:
        ipv4_address: 172.20.0.15
    ports:
      - "9501:9501"
    volumes:
      - ./data:/app/server-node/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```

> console log

```log
cloud-clipboard-go  | ==  cloud-clip  go verion by Jonnyan404         go1.22.12     (devel)
cloud-clipboard-go  | 2025/05/06 14:55:10 服务器错误: listen tcp 0.0.0.0:9501: bind: address already in use
cloud-clipboard-go  | Auth is bool: false
cloud-clipboard-go  | Host[0]: 0.0.0.0
cloud-clipboard-go  | Host[1]: ::1
cloud-clipboard-go  | == uploads directory Exists
cloud-clipboard-go  | Auth is bool: false
cloud-clipboard-go  | Host[0]: 0.0.0.0
cloud-clipboard-go  | Host[1]: ::1
cloud-clipboard-go  | == serve from builtin static
cloud-clipboard-go  | ===== Cloud Clipboard Server go verion by Jonnyan404 =====
cloud-clipboard-go  | Storage: /app/server-node/data/
cloud-clipboard-go  | --- 监听地址: 0.0.0.0:9501
cloud-clipboard-go  | --- 监听地址: [::1]:9501
cloud-clipboard-go  | 启动 HTTP 服务器在 [::1]:9501
cloud-clipboard-go  | 启动 HTTP 服务器在 0.0.0.0:9501
cloud-clipboard-go  | ==  cloud-clip  go verion by Jonnyan404         go1.22.12     (devel)
cloud-clipboard-go  | Auth is bool: false
cloud-clipboard-go  | Host[0]: 0.0.0.0
cloud-clipboard-go  | Host[1]: ::1
cloud-clipboard-go  | == uploads directory Exists
cloud-clipboard-go  | Auth is bool: false
cloud-clipboard-go  | Host[0]: 0.0.0.0
cloud-clipboard-go  | Host[1]: ::1
cloud-clipboard-go  | == serve from builtin static
cloud-clipboard-go  | ===== Cloud Clipboard Server go verion by Jonnyan404 =====
cloud-clipboard-go  | Storage: /app/server-node/data/
cloud-clipboard-go  | --- 监听地址: 0.0.0.0:9501
cloud-clipboard-go  | --- 监听地址: [::1]:9501
cloud-clipboard-go  | 启动 HTTP 服务器在 [::1]:9501
cloud-clipboard-go  | 启动 HTTP 服务器在 0.0.0.0:9501
cloud-clipboard-go  | 2025/05/06 14:55:36 服务器错误: listen tcp 0.0.0.0:9501: bind: address already in use
```

可以明确宿主机的9501并没被使用
