### ISSUE TITLE
address already in use

### ISSUE THREAD

**Issue by 823302271** [Jonnyan404/cloud-clipboard-go#6]
```
cloud-clipboard-go  | Neither manual SSL paths nor MKCERT_DOMAIN_OR_IP are set. SSL is disabled.
cloud-clipboard-go  | #####Generating configuration file#####
cloud-clipboard-go  | ==  cloud-clip  go verion by Jonnyan404         go1.22.12     (devel)
cloud-clipboard-go  | Auth is bool: false
cloud-clipboard-go  | Host[0]: 0.0.0.0
cloud-clipboard-go  | Host[1]: ::1
cloud-clipboard-go  | 2025/05/08 02:49:49 ++ history.json is empty or non-exist, will create
cloud-clipboard-go  | 2025/05/08 02:49:49 ++ uploads directory Created
cloud-clipboard-go  | Auth is bool: false
cloud-clipboard-go  | Host[0]: 0.0.0.0
cloud-clipboard-go  | Host[1]: ::1
cloud-clipboard-go  | == serve from builtin static
cloud-clipboard-go  | ===== Cloud Clipboard Server go verion by Jonnyan404 =====
cloud-clipboard-go  | Storage: /app/server-node/data/
cloud-clipboard-go  | --- 监听地址: 0.0.0.0:9501
cloud-clipboard-go  | --- 监听地址: [::1]:9501
cloud-clipboard-go  | 启动 HTTP 服务器在 [::1]:9501
cloud-clipboard-go  | 启动 HTTP 服务器在 0.0.0.0:9501
cloud-clipboard-go  | 2025/05/08 02:49:49 服务器错误: listen tcp 0.0.0.0:9501: bind: address already in use
```
 
使用docker-compose搭建cloud-clipboard-go 配置- LISTEN_IP=0.0.0.0 会触发端口被占用的问题。如果修改为127.0.0.1 无法访问 
docker-compose.yml->
```
services:
  cloud-clipboard-go:
    container_name: cloud-clipboard-go
#    restart: always
    ports:
      - "9500:9501"
    environment:
 #     - LISTEN_IP=127.0.0.1  # 默认监听所有网卡
      - LISTEN_PORT=9501   # 默认端口
      - PREFIX=            # 子路径为空
      - MESSAGE_NUM=10000  # 历史记录数量设为50
      - AUTH_PASSWORD=     # 默认不设密码
      - TEXT_LIMIT=40960   # 文本长度限制默认值
      - FILE_EXPIRE=604800 # 文件过期时间7天
      - FILE_LIMIT=2048000 
    volumes:
      - ./data:/app/server-node/data  # 数据存储在当前目录的data文件夹
    image: jonnyan404/cloud-clipboard-go:latest
```
